development:
  adapter: postgresql
  encoding: unicode
  database: sample_app2_development
  pool: 5
  username: postgres
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app2_test
  pool: 5
  username: postgres
  password: 